// The six topics and their sub-topics, English + Afrikaans.
// Afrikaans terms are lifted from Megan's own Sept Paper II AFR sources
// (boks-en-snor-diagram, verkleiningsformules, interkwartielomvang,
//  koordevierhoek, eweredigheidstelling, hoogtehoek, dubbelhoekformule).
// `syn` holds extra words that SEARCH should match but that are not printed —
// classroom shorthand in both languages, plus common misspellings.

export const TOPICS = [
  {
    id: 'stat', accent: 's3',
    en: 'Statistics', af: 'Statistiek',
    syn: ['stats', 'data', 'statistieke'],
    subs: [
      { id: 'stat-scatter', en: 'Scatter plots & the regression line', af: 'Spreidiagramme & die regressielyn',
        syn: ['least squares', 'line of best fit', 'kleinste kwadrate', 'beste passing', 'regression', 'regressie', 'y = a + bx'] },
      { id: 'stat-corr', en: 'Correlation coefficient', af: 'Korrelasiekoëffisiënt',
        syn: ['r value', 'r waarde', 'strength of correlation', 'sterkte', 'korrelasie', 'positive', 'negative'] },
      { id: 'stat-outlier', en: 'Outliers', af: 'Uitskieters',
        syn: ['outlier', 'uitskieter', 'anomaly', 'afwyking', '1,5 x IQR', 'IKV'] },
      { id: 'stat-box', en: 'Box-and-whisker & quartiles', af: 'Boks-en-snor-diagram & kwartiele',
        syn: ['box plot', 'kwartiel', 'median', 'mediaan', 'interquartile range', 'interkwartielomvang', 'IQR', 'five number summary', 'vyfgetalopsomming'] },
      { id: 'stat-sd', en: 'Standard deviation & variance', af: 'Standaardafwyking & variansie',
        syn: ['sigma', 'sd', 'spread', 'verspreiding', 'mean', 'gemiddeld', 'afwyking'] },
      { id: 'stat-ogive', en: 'Ogive (cumulative frequency)', af: 'Ogief (kumulatiewe frekwensie)',
        syn: ['ogive', 'ogief', 'cumulative', 'kumulatief', 'frequency polygon', 'frekwensiepoligoon', 'histogram'] },
      { id: 'stat-skew', en: 'Skewness & symmetry', af: 'Skeefheid & simmetrie',
        syn: ['skewed', 'skeef', 'symmetric', 'simmetries', 'left', 'right', 'links', 'regs'] },
    ],
  },
  {
    id: 'ana', accent: 's4',
    en: 'Analytical Geometry', af: 'Analitiese Meetkunde',
    syn: ['analytical geo', 'analitiese geo', 'coordinate geometry', 'koördinaatmeetkunde', 'analytic'],
    subs: [
      { id: 'ana-basics', en: 'Distance, midpoint & gradient', af: 'Afstand, middelpunt & helling',
        syn: ['distance formula', 'afstandformule', 'midpoint', 'middelpunt', 'gradient', 'helling', 'slope'] },
      { id: 'ana-line', en: 'Equation of a straight line', af: 'Vergelyking van ’n reguitlyn',
        syn: ['straight line', 'reguitlyn', 'y = mx + c', 'equation of the line', 'lynvergelyking'] },
      { id: 'ana-parperp', en: 'Parallel & perpendicular lines', af: 'Ewewydige & loodregte lyne',
        syn: ['parallel', 'ewewydig', 'perpendicular', 'loodreg', 'm1 m2 = -1'] },
      { id: 'ana-incl', en: 'Angle of inclination', af: 'Hoek van inklinasie',
        syn: ['inclination', 'inklinasie', 'tan theta', 'angle between two lines', 'hoek tussen twee lyne'] },
      { id: 'ana-circle', en: 'Circle: standard & general form', af: 'Sirkel: standaard- & algemene vorm',
        syn: ['circle equation', 'sirkelvergelyking', 'completing the square', 'volkome vierkant', 'centre and radius', 'middelpunt en radius', 'general form', 'algemene vorm'] },
      { id: 'ana-tangent', en: 'Tangent to a circle', af: 'Raaklyn aan ’n sirkel',
        syn: ['tangent', 'raaklyn', 'point of contact', 'raakpunt', 'touches'] },
      { id: 'ana-quad', en: 'Proving quadrilaterals & triangles', af: 'Vierhoeke & driehoeke bewys',
        syn: ['parallelogram', 'rhombus', 'ruit', 'rectangle', 'reghoek', 'show that', 'toon aan', 'collinear', 'kollineêr'] },
      { id: 'ana-transform', en: 'Reflection & transformation', af: 'Weerkaatsing & transformasie',
        syn: ['reflection', 'weerkaatsing', 'spieëlbeeld', 'reflect about', 'rotation', 'rotasie', 'translation'] },
      { id: 'ana-area', en: 'Area & perimeter in the plane', af: 'Oppervlakte & omtrek in die vlak',
        syn: ['area of triangle', 'oppervlakte van driehoek', 'perimeter', 'omtrek'] },
    ],
  },
  {
    id: 'trig', accent: 's2',
    en: 'General Trigonometry', af: 'Algemene Trigonometrie',
    syn: ['trig', 'trigonometry', 'trigonometrie', 'general trig', 'algemene trig'],
    subs: [
      { id: 'trig-reduce', en: 'Reduction formulae', af: 'Verkleiningsformules',
        syn: ['reductions', 'trig reductions', 'reduksie', 'verkleining', 'verkleinings', '180 - x', '360 - x', 'CAST', 'quadrants', 'kwadrante', 'co-functions', 'kofunksies'] },
      { id: 'trig-special', en: 'Special angles (no calculator)', af: 'Spesiale hoeke (sonder sakrekenaar)',
        syn: ['special angles', 'spesiale hoeke', '30 45 60', 'without a calculator', 'sonder sakrekenaar', 'OATS', 'surd form', 'wortelvorm'] },
      { id: 'trig-ident', en: 'Proving identities', af: 'Identiteite bewys',
        syn: ['identity', 'identiteit', 'prove that', 'bewys dat', 'LHS RHS', 'LK RK', 'simplify', 'vereenvoudig', 'undefined', 'ongedefinieerd'] },
      { id: 'trig-gensol', en: 'General solution & solving equations', af: 'Algemene oplossing & vergelykings oplos',
        syn: ['general solution', 'algemene oplossing', 'solve for x', 'los op vir x', 'k in Z', 'interval', 'how many solutions', 'hoeveel oplossings'] },
      { id: 'trig-compound', en: 'Compound angles', af: 'Samegestelde hoeke',
        syn: ['compound angle', 'samegestelde hoek', 'sin(A + B)', 'cos(A - B)', 'expansion', 'uitbreiding', 'som en verskil'] },
      { id: 'trig-double', en: 'Double angle formulae', af: 'Dubbelhoekformules',
        syn: ['double angle', 'dubbelhoek', 'sin 2A', 'cos 2A', 'dubbele hoek'] },
      { id: 'trig-rules', en: 'Sine, cosine & area rules (2D)', af: 'Sinus-, cosinus- & oppervlaktereël (2D)',
        syn: ['sine rule', 'sinusreël', 'cosine rule', 'cosinusreël', 'area rule', 'oppervlaktereël', 'ambiguous case', 'proof of the sine rule', 'bewys van die sinusreël'] },
      { id: 'trig-ratio', en: 'Ratios from a diagram or a given value', af: 'Verhoudings uit ’n figuur of gegewe waarde',
        syn: ['if sin x = p', 'as sin x = p', 'in terms of p', 'in terme van p', 't-triangle', 'sketch the angle', 'skets die hoek'] },
    ],
  },
  {
    id: 'tgraph', accent: 's5',
    en: 'Trig Graphs', af: 'Trig Grafieke',
    syn: ['trig graphs', 'trigonometriese grafieke', 'graphs', 'grafieke', 'sin cos tan graphs'],
    subs: [
      { id: 'tg-sketch', en: 'Sketching sin, cos and tan', af: 'Sin, cos en tan skets',
        syn: ['sketch the graph', 'skets die grafiek', 'draw', 'teken', 'on the same axes', 'op dieselfde asse'] },
      { id: 'tg-apst', en: 'Amplitude, period & shifts', af: 'Amplitude, periode & verskuiwings',
        syn: ['amplitude', 'period', 'periode', 'shift', 'verskuiwing', 'translation', 'vertical shift', 'horizontal shift', 'a b c waardes'] },
      { id: 'tg-inter', en: 'Points of intersection', af: 'Snypunte',
        syn: ['intersection', 'snypunt', 'snypunte', 'where the graphs meet', 'waar die grafieke sny', 'f = g'] },
      { id: 'tg-ineq', en: 'Reading inequalities off the graph', af: 'Ongelykhede vanaf die grafiek',
        syn: ['inequality', 'ongelykheid', 'ongelykhede', 'f(x) > g(x)', 'greater than', 'increasing', 'stygend', 'when is the graph positive', 'waar is die grafiek positief'] },
      { id: 'tg-domran', en: 'Domain & range', af: 'Definisieversameling & waardeversameling',
        syn: ['domain', 'range', 'definisieversameling', 'waardeversameling', 'gebied', 'maximum value', 'maksimum waarde'] },
    ],
  },
  {
    id: 't3d', accent: 'ink',
    en: '3D Trigonometry', af: '3D Trigonometrie',
    syn: ['3d trig', '3d', 'drie dimensies', 'three dimensional', 'driedimensioneel', '3d trigonometrie'],
    subs: [
      { id: 't3d-elev', en: 'Angles of elevation & depression', af: 'Hoogte- & diepteshoeke',
        syn: ['elevation', 'hoogtehoek', 'depression', 'dieptehoek', 'angle of elevation', 'tower', 'toring', 'mast', 'mas', 'pole', 'paal'] },
      { id: 't3d-rules', en: 'Sine & cosine rule in 3D', af: 'Sinus- & cosinusreël in 3D',
        syn: ['sine rule 3d', 'cosine rule 3d', 'sinusreël', 'cosinusreël', 'which triangle first', 'watter driehoek eerste'] },
      { id: 't3d-planes', en: 'Two planes & the line between them', af: 'Twee vlakke & die lyn tussen hulle',
        syn: ['horizontal plane', 'horisontale vlak', 'vertical', 'vertikaal', 'perpendicular to the plane', 'loodreg op die vlak', 'same plane', 'dieselfde vlak'] },
      { id: 't3d-proof', en: 'Proving a 3D result (show that…)', af: 'Bewysvrae in 3D (toon aan dat…)',
        syn: ['show that', 'toon aan dat', 'hence', 'vervolgens', 'in terms of', 'in terme van', 'prove', 'bewys'] },
    ],
  },
  {
    id: 'euc', accent: 's1',
    en: 'Euclidean Geometry', af: 'Euklidiese Meetkunde',
    syn: ['euclid', 'euclidean', 'euklidies', 'geometry', 'meetkunde', 'circle geometry', 'sirkelmeetkunde', 'geo'],
    subs: [
      { id: 'euc-centre', en: 'Angle at the centre', af: 'Hoek by die middelpunt',
        syn: ['angle at centre', 'hoek by middelpunt', 'twice the angle', 'dubbel die hoek', 'middelpuntshoek'] },
      { id: 'euc-semi', en: 'Angle in a semicircle', af: 'Hoek in ’n halfsirkel',
        syn: ['semicircle', 'halfsirkel', 'diameter', '90 degrees', 'angle in semi circle'] },
      { id: 'euc-segment', en: 'Angles in the same segment', af: 'Hoeke in dieselfde segment',
        syn: ['same segment', 'dieselfde segment', 'equal angles', 'gelyke hoeke'] },
      { id: 'euc-cyclic', en: 'Cyclic quadrilaterals', af: 'Koordevierhoeke',
        syn: ['cyclic quad', 'koordevierhoek', 'siklies', 'opposite angles', 'oorstaande hoeke', 'exterior angle', 'buitehoek', 'prove cyclic', 'bewys siklies'] },
      { id: 'euc-tanchord', en: 'Tangent-chord (tan-chord) theorem', af: 'Raaklyn-koordstelling',
        syn: ['tan chord', 'tangent chord', 'raaklyn koord', 'raaklynkoordstelling', 'alternate segment', 'afwisselende segment'] },
      { id: 'euc-tangents', en: 'Tangents from a point & radius⊥tangent', af: 'Raaklyne vanaf ’n punt & radius⊥raaklyn',
        syn: ['two tangents', 'twee raaklyne', 'tangents equal', 'raaklyne gelyk', 'radius perpendicular', 'radius loodreg'] },
      { id: 'euc-chords', en: 'Chords, perpendicular from centre', af: 'Koorde, loodlyn vanaf middelpunt',
        syn: ['chord', 'koord', 'koorde', 'bisects', 'halveer', 'perpendicular from the centre', 'loodlyn vanaf die middelpunt'] },
      { id: 'euc-prop', en: 'Proportionality theorem (parallel lines)', af: 'Eweredigheidstelling (ewewydige lyne)',
        syn: ['proportionality', 'eweredigheid', 'eweredigheidstelling', 'proportion', 'basic proportionality', 'line parallel to one side', 'lyn ewewydig aan een sy', 'midpoint theorem', 'middelpuntstelling'] },
      { id: 'euc-similar', en: 'Similar triangles', af: 'Gelykvormige driehoeke',
        syn: ['similar', 'gelykvormig', 'gelykvormige driehoeke', 'equiangular', 'gelykhoekig', 'ratio of sides', 'verhouding van sye', '|||'] },
      { id: 'euc-proof', en: 'Bookwork proofs (the theorems)', af: 'Bewerkte bewyse (die stellings)',
        syn: ['bookwork', 'bewerkte bewys', 'prove the theorem', 'bewys die stelling', 'proof', 'bewys', 'stelling'] },
    ],
  },
];

// Topic key used on the paper side comes from the papers' own fingerprint files
// (STAT / ANA / TRIG / EUC). Trig graphs and 3D trig live inside TRIG there.
export const PAPER_TOPIC_LABEL = {
  stat: { en: 'Statistics', af: 'Statistiek', accent: 's3' },
  ana: { en: 'Analytical Geometry', af: 'Analitiese Meetkunde', accent: 's4' },
  trig: { en: 'Trigonometry', af: 'Trigonometrie', accent: 's2' },
  euc: { en: 'Euclidean Geometry', af: 'Euklidiese Meetkunde', accent: 's1' },
};
